services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "8501:8501"
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  kmp-pdf-intelligence:
    image: bert-testing-kmp-pdf-intellegence:latest
    build: .
    network_mode: "service:ollama"
    depends_on:
      - ollama
    volumes:
      - ./Data:/app/Data

volumes:
  ollama:
